config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :tents do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy] do
    get "confirmation", to: "bookings#confirmation", as: :confirmation
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tent
end

app/models/tent.rb
class Tent < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tents
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def confirmation
    @booking = Booking.find(params[:booking_id])
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
    # @tent = Tent.new
    @past_bookings = current_user.bookings.where("start_date < ?", Date.today).order(start_date: :desc)
    @future_bookings = current_user.bookings.where("start_date >= ?", Date.today).order(start_date: :desc)
  end

  def show
    set_booking
    @tent = @booking.tent
    @markers = [
      {
        lat: @tent.latitude,
        lng: @tent.longitude,
        info_window: render_to_string(partial: "tents/info_window", locals: { tent: @tent }),
        image_url: helpers.asset_path("tipi_map_logo.png")
      }
    ]
  end

  def new
    @booking = Booking.new
  end

  def create
    @tent = Tent.find(params[:tent_id])
    @booking = Booking.new(booking_params)
    @booking.tent = @tent
    @booking.user = current_user
    # @booking.status = "Pending Host Validation"
    if @booking.save!
      redirect_to booking_confirmation_path(@booking)
    else
      redirect_to tent_path(@tent), :unprocessable_entity
    end
  end

  def update
    set_booking
    @booking.status = "Pending Host Validation."
    @booking.save
    redirect_to booking_path(@booking)
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to tent_path(@booking.tent), status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # @tent = Tent.new
    # @bookings = Booking.all
    @tents = Tent.last(3)
  end
end

app/controllers/tents_controller.rb
class TentsController < ApplicationController

  def index
    @tents = Tent.all
    @markers = @tents.geocoded.map do |tent|
      {
        lat: tent.latitude,
        lng: tent.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tent: tent }),
        image_url: helpers.asset_path("tipi_map_logo.png")
      }
    end
  end

  def show
    @tent = Tent.find(params[:id])
    @booking = Booking.new
    @markers = [
      {
        lat: @tent.latitude,
        lng: @tent.longitude,
        info_window: render_to_string(partial: "info_window", locals: { tent: @tent }),
        image_url: helpers.asset_path("tipi_map_logo.png")
      }
    ]
  end

  def new
    @tent = Tent.new
  end

  def create
    @tent = Tent.new(tent_params)
    @tent.user = current_user
    if @tent.save
      redirect_to tent_path(@tent)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @tent = Tent.find(params[:id])
    @tent.destroy
    redirect_to tents_path, status: :see_other
  end

  private

  def tent_params
    params.require(:tent).permit(:title, :description, :capacity, :location, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/confirmation.html.erb
<div class="container">
  <div class="row justify-content-center" id="name">
    <div class="col-6">
      <br>
    <h2 class="text-center heading text-primary fs-2 fw-bolder"><strong>Congratulations🎉<br>Your booking has been confirmed!</strong></h2>

      <h3 class="text-center heading text-warning fs-1 fw-bolder"><strong>Your booking details</strong></h3>
        <br>
          <%= cl_image_tag @booking.tent.photo.key, style: "width: 100%", crop: :fill %>
          <br>
            <ul class="list-group">
            <li class="list-group-item text-center fs-4"><strong>Start Date: <%= @booking.start_date %></strong> | <strong>End Date: <%= @booking.end_date %></strong></li>
            <br>
            <li class="list-group-item text-center fs-4"><h4><strong>⛺<%= @booking.tent.title %>⛺</strong></h4></li>
            <li class="list-group-item fs-5"><p>Location: <%= @booking.tent.location %></p></li>
            <li class="list-group-item fs-5"><p><%= @booking.tent.description %></p></li>
            <li class="list-group-item fs-5"><p>Total price: £<% time_difference = @booking.end_date.mjd - @booking.start_date.mjd %>
            <%= time_difference * @booking.tent.price.to_i %></p></li>
            <br>
            <p class="fs-5"><%= link_to "Back to list of tents", tents_path %></p>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="text-center">
  <h1 class="heading text-warning fw-bolder">My Bookings</h1>
</div>

<div class="container">
  <h2 class = "heading text-primary fs-1 fw-bolder">Upcoming Bookings</h2>
  <div class="cards">
      <% @future_bookings.each do |booking| %>
        <%# <% if booking.photo.attached? %>
        <%= link_to booking_path(booking) do   %>
          <div class="card-trip">
            <%= cl_image_tag booking.tent.photo.key, height: 300, width: 350, crop: :fill %>
            <div class="card-trip-infos">
              <div>
                 <%= booking.tent.title %>
                <br>
                <p>Location: </p><%= booking.tent.location %>
                <br>
                <p>From: </p><%= booking.start_date.strftime('%d %b %Y') %> to <%= booking.end_date.strftime('%d %b %Y') %>
                <br>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

<div class="container">
  <h2 class="heading text-primary fs-1 fw-bolder">Past Bookings</h2>
    <div class="cards">
      <% @past_bookings.each do |booking| %>
        <%# <% if booking.photo.attached? %>
        <%= link_to booking_path(booking) do %>
          <div class="card-trip">
            <%= cl_image_tag booking.tent.photo.key, height: 300, width: 350, crop: :fill %>
            <div class="card-trip-infos">
            <div>
            <%= booking.tent.title %>
            <br>
            <p>Location: </p><%= booking.tent.location %>
            <br>
            <p>From: </p><%= booking.start_date.strftime('%d %b %Y') %> to <%= booking.end_date.strftime('%d %b %Y') %>
            <br>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Book a tent!</h1>

<%= simple_form_for(@tent, @booking) do |f| %>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :email %>
<%= f.input :start_date %>
<%= f.input :end_date %>

<%= f.submit "Confirm my booking", class: "btn btn-danger btn-lg" %>
<% end %>

app/views/bookings/show.html.erb
<div class="container d-flex mt-5">
  <div class="row justify-content-center" id="name" style="max-width: 50vw;">
    <div class="col-12 px-5 map" style="text-align: center;">
      <h1><%= @booking.tent.title %></h1>
      <br>
      <%= cl_image_tag @booking.tent.photo.key, style: "width: 100%", crop: :fill, class: "img" %>
      <br>
      <ul style= "padding: 0">
        <li class="list-group-item">Description: <%= @booking.tent.description %></li>
        <li class="list-group-item">Capacity: <%= @booking.tent.capacity %></li>
        <li class="list-group-item">Location: <%= @booking.tent.location %></li>
        <li class="list-group-item">Booking Date: <%= @booking.start_date.strftime('%d %b %Y') %> to <%= @booking.end_date.strftime('%d %b %Y') %></li>
        <li class="list-group-item">Price: £<%= @booking.tent.price.to_i %></li>
      </ul>
    </div>
  </div>
  <div class="map" style="width: 100%; height: 682px; margin: auto;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <title>WanderlustTents</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
 <div class="box-container">
  <div class="banner text-center">
    <div class="banner-content">
      <h1 class="text-warning" id="main-title">Protect your next adventure<br>with our tents!</h1>
      <%# <form action="/tents" class="form-inline">
      <div class="row-cols-lg-auto">
        <div class="col-8">
          <input name="text" class="form-control input-lg" placeholder="Location?">
        </div>
        <div class="col-2">
          <input type="submit" class="btn btn-warning btn-md mt-3" value="Search">
        </div>
      </div> %>
      <form class="row row-cols-lg-auto g-3 align-items-center" id="searchbar">
  <div class="col-12">
    <label class="visually-hidden" for="inlineFormInputGroupUsername">Username</label>
    <div class="input-group">
      <div class="input-group-text fs-4">📍</div>
      <input type="text" class="form-control fs-5" id="inlineFormInputGroupUsername" placeholder="Location?">
    </div>
  </div>
  <div class="col-12 btn-lg">
    <div class="new-button"><%= link_to "Search", tents_path %></div>
  </div>
        </div>
      </form>
    </div>
  </div>

  <div class="box-container">
    <h1 class="heading text-primary fw-bolder">⛰️ Featured Tents ⛰️</h1>
    <div class="cards">
        <% @tents.each do |tent| %>
          <% if tent.photo.attached?%>
            <%= link_to tent_path(tent) do %>
              <div class="card-trip">
                <%= cl_image_tag tent.photo.key, height: 300, width: 500, crop: :fill %>
                <div class="card-trip-infos">
                  <div>
                    <span><%= tent.title %></span>
                    <br>
                    📍 <span class="locationcolor"><%= tent.location %></span>
                    <br>
                    £<span><%= tent.price.to_i %></span>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </div>

  <section class="icons-container box-container homepage-background">

      <div class="icons">
          <%= image_tag "icon-1.png", id: "background" %>
          <div class="info">
              <h3>free delivery & pickup</h3>
              <span>on all orders</span>
          </div>
      </div>

      <div class="icons">
        <%= image_tag "icon-2.png", id: "background" %>
          <div class="info">
              <h3>10 days returns</h3>
              <span>moneyback guarantee</span>
          </div>
      </div>

      <div class="icons">
      <%= image_tag "icon-4.png", id: "background" %>
          <div class="info">
              <h3>secure payments</h3>
              <span>protected by paypal</span>
          </div>
      </div>

  </section>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style='position: sticky; top: 0; z-index: 1;'>
  <div class="container-fluid">
    <%= link_to root_path "#", class: "navbar-brand" do %>
    <header class="fs-4">⛺ WANDERLUST</header>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <nav class="navbar text-align-right">
        <%= link_to "Products", tents_path, class: "nav-link" %>
        <%= link_to "List a Tent", new_tent_path, class: "nav-link" %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">

          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/usmanaman", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "nav-link dropdown-item navbar-dropdown-color" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item navbar-dropdown-color" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link", id: "logincolor" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
      </nav>

</div>

app/views/tents/_info_window.html.erb
<h4><%= tent.title %></h4>
<p><%= tent.location %></p>

app/views/tents/index.html.erb
  <div class="container">
    <h1 class="heading text-warning fw-bolder">🏕 <strong> Tents for hire! </strong> 🏕</h1>
    <div class="cards">
        <% @tents.each do |tent| %>
          <% if tent.photo.attached?%>
            <%= link_to tent_path(tent) do %>
              <div class="card-trip">
                <%= cl_image_tag tent.photo.key, height: 300, width: 500, crop: :fill %>
                <div class="card-trip-infos">
                  <div>
                    <span><%= tent.title %></span>
                    <br>
                    📍 <span class="locationcolor"><%= tent.location %></span>
                    <br>
                    £<span><%= tent.price.to_i %></span>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
    </div>
    <br>
    <div class="map" style="width: 100%; height: 600px;"
      data-controller="map"
      data-search="true"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <br>
  </div>

app/views/tents/new.html.erb
<div class="container">
  <div class="row">
  <h2 class="text-center heading text-primary fs-1 fw-bolder">🏕️ Share your tent with the outdoor community 🏕️</h2>
    <div class="text-left form-login fs-3">
      <br>
      <%= simple_form_for(@tent) do |f| %>
      <%= f.input :title, label: "Your tent's make and model:", placeholder: "Trango Tower tent", :label_html => { :class => "label-css"} %>
      <%= f.input :capacity, label: "Tent capacity:", placeholder: "1, 2, 3?" %>
      <%= f.input :location, input_html: {data: {location_autocomplete_target: "location"}, class:'d-none'}, wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}, placeholder: "City or Postcode" %>
      <%= f.input :description, label: "A brief description of your tent:", placeholder: "Can easily fit two people and a dog! Plus it is 100% waterproof and breathable!" %>
      <%= f.input :price, label: "Price per day in £:", placeholder: "48" %>
      <br>
      <%= f.input :photo, as: :file, label: "Choose a nice picture of your tent!" %>
      <br>
      <%= f.submit class: "btn btn-warning btn-lg"%>
      <% end %>
      <br>
      <%= link_to "Back to tents", tents_path, class: "btn btn-warning btn-lg" %>
    </div>
  </div>
</div>

app/views/tents/show.html.erb
<div class="container d-flex mt-5">
  <div class="row justify-content-center" id="name">
    <div class="col-6 map">
      <h1 class="heading text-primary fw-bolder"><%= @tent.title %></h1>
      <%= cl_image_tag @tent.photo.key, style: "width: 100%", crop: :fill, class: "img" %>
      <ul class="list-group fs-5 show-ul">
        <li class="list-group-item">⛺ <%= @tent.description %></li>
        <li class="list-group-item">🧍🏼‍♂️ Capacity: <%= @tent.capacity %></li>
        <li class="list-group-item">📍 Location: <%= @tent.location %></li>
        <li class="list-group-item">💸 Price: £<%= @tent.price %></li>
      </ul>
      <br>
      <p class="fs-5"><%= link_to "Back to tents", tents_path, class: "btn btn-warning btn-lg" %></p>
    </div>

  <div class="col-6 fs-5">
    <h1 class="heading text-warning fw-bolder">Book this tent ✔️</h1>
      <%= simple_form_for [@tent, @booking] do |f| %>
      <%= f.input :start_date, html5: true %>
      <%= f.input :end_date, html5: true %>
      <%= f.submit :Confirm %>
    <% end %>
    <br>
    <div class="map" style="width: 100%; height: 600px; margin: auto;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>